"""initial migration

Revision ID: cbf74ac8f61c
Revises: 
Create Date: 2017-11-10 14:52:06.276603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbf74ac8f61c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obs_user', sa.Column('test', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obs_user', 'test')
    # ### end Alembic commands ###
